### ISSUE TITLE
add_requiredStatement not accepting entry with included language

### ISSUE THREAD

**Issue by martimpassos** [giacomomarchioro/pyIIIFpres#10]
Hi Giacomo, not sure if you plan on maintaining this package with Prezi3 in the works, but I'm trying to add required statement via `entry` and getting 
```
AssertionError: Language must be a valid BCP47 language tag or none. Please read https://git.io/JoQty.
```
I'm using `pt-BR`, which is included by `iiifpapi3.LANGUAGES = ["pt-BR", "en"]`, in pretty much all other fields without a problem. 

If I use the `label`, `value`, `language_v`, `language_l` form it accepts `pt-BR`, but ends up overwriting the `en` block in the final manifest. Is this the desired behavior? All other `add_` methods work multiple times. Maybe it should be `set_requiredstatement`?

**Comment by martimpassos** [comment]
```
iiifpapi3.LANGUAGES = ["pt-BR", "en"]
```
```
manifest.add_label("pt-BR", item["Title"]) # works fine

required = {
        "label": {"en": ["Hosting"], "pt-BR": ["Hospedagem"]},
        "value": {
            "en": ["Hosted by imagineRio"],
            "pt-BR": ["Hospedado por imagineRio"],
        },
    }

manifest.add_requiredStatement(entry=required) # raises AssertionError
```
```
    manifest.add_requiredStatement( # works fine
        label="Hosting",
        value="Hosted by imagineRio",
        language_l="en",
        language_v="en",
    )

    manifest.add_requiredStatement( # also works, but overwrites en entry
        label="Hospedagem",
        value="Hospedado por imagineRio",
        language_l="pt-BR",
        language_v="pt-BR",
    )
```

**Comment by giacomomarchioro** [comment]
Thanks Martim, I think should be added only once so you are right that it should be a set method. I will have a look to the the error that you have in the next hours. 
Thanks for your precious feedback!

**Comment by giacomomarchioro** [comment]
I have checked the spec: 
https://github.com/IIIF/presentation-validator/blob/90197c88d8676c652cf475909bf34ab689fb6ea0/schema/iiif_3_0.json#L367

Only one required statement is allowed, but rememeber that add_requiredStatement return a Multilanguage object if you leave it empty so you can do something like this for your purpose:


```
reqst = manifest.add_requiredStatement()
reqst.add_label('Hosting','en') 
reqst.add_value('hosted by imagineRio','en') 
reqst.add_label('Hospedagem','pt-BR')
reqst.add_value('Hospedado per imagineRio','pt-BR')
```

**Comment by martimpassos** [comment]
Got it. However, the `entry` form not accepting pt-BR is a bug?

**Comment by giacomomarchioro** [comment]
Yes, I have just pushed a patch for this bug:
https://github.com/giacomomarchioro/pyIIIFpres/commit/71b5d26853b9433629e20f24312cc5459ae95fd7
Thanks a lot for that. 


I suggest however to try to use `entry` only as a last resort because usually, it should not perform any check when you entry data directly as a dict.  Thanks for your feedbacks!
