### ISSUE TITLE
INVALID_URI_CHARACTERS

### ISSUE THREAD

**Issue by ColeDCrawford** [giacomomarchioro/pyIIIFpres#11]
I'm using a number of URNs as manifest, canvas, and annotation identifiers. They often include colon `:` characters, e.g. `https://nrs-qa.lib.harvard.edu/URN-3:AT:TESTMANIFEST:MANIFEST:3`. `pyIIIFpres` is flagging those in the [`check_valid_URI` method](https://github.com/giacomomarchioro/pyIIIFpres/blob/7b30a6163f4c2ab7cc36b60c231feb2f7aa281dd/IIIFpres/iiifpapi3.py#L182-L193) and throwing an AssertionError, saying that special characters must be encoded.

Where was the list of `INVALID_URI_CHARACTERS` taken from? I'm seeing some IETF RFCs which say `:` shouldn't be used in the path, though it's fine in a fragment. That said, various sites including Wikipedia are using it for namespacing the same way we are (https://en.wikipedia.org/wiki/Template:Welcome), and we're not encountering any issues with colons. Is it possible to whitelist `:`? Or to allow users to pass a string of characters to whitelist? I don't have the ability to change our identifier schema, so forking this is my next best option, which I'd prefer not to do.

**Comment by giacomomarchioro** [comment]
Hi, thanks for reporting this issue I forgot to document this part, you can access the invalid URI characters like this 

```
from IIIFpres import iiifpapi3
iiifpapi3.INVALID_URI_CHARACTERS

```
And modify it like this: 
```
from IIIFpres import iiifpapi3
iiifpapi3.INVALID_URI_CHARACTERS = iiifpapi3.INVALID_URI_CHARACTERS.replace(":","") 
```
Or you can completely empty the string to allow any character:
```
from IIIFpres import iiifpapi3
iiifpapi3.INVALID_URI_CHARACTERS = "" 
```
The list of characters allowed is taken in part from [rfc2396](https://www.ietf.org/rfc/rfc2396.txt) (look for unwise characters) adding some recommendation from [rfc3986](https://www.rfc-editor.org/rfc/rfc3986#section-3.3).

You are right that `:` is often safe to use, sometime in some exceptional cases it could be mistaken for the protocol scheme. 
My idea was to be as strict as possible and let the user loosen the checks depending on their needs, but probably I should remove this character from this list by default.

**Comment by ColeDCrawford** [comment]
Overriding this worked fine, thanks!

**Comment by giacomomarchioro** [comment]
You are welcome, let me know if you need any further help, best regards!
