### ISSUE TITLE
PyPi?

### ISSUE THREAD

**Issue by ColeDCrawford** [giacomomarchioro/pyIIIFpres#12]
Would it be possible to release this on PyPi? I have a library which uses this as a dependency, and will need to remove pyIIIFpres as a direct dependency (`install_requires`) in my setup if it's not on PyPi, as PyPi requires that direct dependencies also be available on PyPi.

**Comment by giacomomarchioro** [comment]
Hi thanks for your feedback, 
I have uploaded it to PyPI here is the link: 
https://pypi.org/project/pyIIIFpres/0.1.1/

`pip install pyIIIFpres==0.1.1`

Let me know if you find any problems. 

Best regards, 
Giacomo

**Comment by ColeDCrawford** [comment]
Awesome, thank you! Very helpful
