### ISSUE TITLE
A better way to validate manifest objects

### ISSUE THREAD

**Issue by martimpassos** [giacomomarchioro/pyIIIFpres#13]
Hi Giacomo, if I want to validate a manifest before it gets written to a file, I need to do 
```
jsonschema.validate(instance=json.loads(manifest.json_dumps()), schema=json.load(schema))
```
to turn a Manifest object into JSON object. `manifest.json_dumps()` will give me a string that doesn't work with the validator. Maybe it would be useful to have a `to_json` method to make this cleaner?
```
def to_json(self):
  return json.loads(self.json_dumps())

jsonschema.validate(instance=manifest.to_json(), schema=json.load(schema))
```

**Comment by giacomomarchioro** [comment]
Hi Martim, that would be great!

Would you like to do a pull-request? You could add the function you wrote after this line:

https://github.com/giacomomarchioro/pyIIIFpres/blob/fc1fd56d68aa8349b37fc5a1725849db14dc3c06/IIIFpres/iiifpapi3.py#L361

Otherwise I can do it. 

Thanks for your feedback!

**Comment by martimpassos** [comment]
Sure, I can do it. I'll include `json_dumps` arguments in `to_json` so the user can fine tune the object creation, does that sound good? Also, is there need for a `to_orjson` method as well? (I'm curious about the performance improvement using `orjson` for IIIF manifests, have you benchmarked this?)

**Comment by giacomomarchioro** [comment]
Hi Martim, thanks for your contribution. 

Yes orjson is much faster so a similar method could be helpful, I don't know how many people generate manifest on the fly 
https://github.com/giacomomarchioro/pyIIIFpres/wiki/Improve-performance-of-writing-and-serving-JSON-IIIF-objects
here is the article that treats the performance improvements tricks, feel free to add a pull request with your testing result that you can run after cloning the repository as explained in the article.
