### ISSUE TITLE
Remove item from collection

### ISSUE THREAD

**Issue by martimpassos** [giacomomarchioro/pyIIIFpres#15]
Because `collection.items` is a list of Manifest objects, I'm currently doing 
```
for item in collection.items:
  if f"{id}/manifest" in item.id:
    collection.items.remove(item)
```
to check for duplicates. The specification doesn't say collections couldn't have the same manifest over and over again (although I can't think of a scenario where this would be wanted) so I don't think forcing collections to have unique ids is the way to go, but a method to remove an item by `id` could be useful: 
```
def remove_item(self, id_to_remove):
  for item in self.items:
    if item.id == id_to_remove:
      self.items.remove(item)

OR 

def remove_item(self, id_to_remove)
  self.items = list(filter(lambda x: x.id != id_to_remove, self.items))
```
So I could do 
```
if id in [item.id for item in collection.items]:
  collection.remove_item(id)
```
Even better would be something like
```
if id in collection.items.id:   # turn items into {"id":[ids],"manifest":[manifests]}?
  collection.remove_item(id)

OR

if id in collection.ids:  # create a new property with ids only?
  collection.remove_item(id)
```

**Comment by giacomomarchioro** [comment]
Hi martim, there is a similar method in the utilities module: https://github.com/giacomomarchioro/pyIIIFpres/wiki/Reading-and-modifying-JSON-compliant-with-API-3.0 could this solve the issue? 

P.S. there is a hackathon next Friday for the official module if you want to join: https://docs.google.com/forms/d/e/1FAIpQLSexhowC7f2uYuiwYPY83ITYsZNgJqo_5VnEt8YN1t46rq2OUw/viewform?usp=send_form

**Comment by martimpassos** [comment]
`remove_and_insert_new` seems to be along the lines of what I'm looking for. However, there seems to be a bug in the recursion as you call the function without the `newobj` argument. I also understand the function works on whatever has an `id` property (manifest, collection, canvas, etc), but that is unclear.

Furthermore, calling `remove_item_byID` on a single-item collection results in an empty collection, something that is not allowed when normally creating it:

```
self.items = Required(
            "A collection object must have at least one item!")
```

**Comment by martimpassos** [comment]
`remove_and_insert_new` would allow to merge object removal and appending into a single command, but it does not tackle iterating through collection items in a cleaner way... I'm still left with 
```
for item in collection.items:
  if item.id == "id_to_check": # or "id_to_check" in item.id
    remove_and_insert_new(collection, "id_to_check", new_manifest)
```
I suppose if the function raised an exception when the id isn't found I could default to 
```
try:
  remove_and_insert_new(collection, "id_to_check", new_manifest)
except KeyError: # or something like that
 collection.add_manifest_to_items(new_manifest)
```
but IMO something like
```
if id in collection.items.keys(): # items is a {id:manifest} dict in this case
  remove_and_insert_new(collection, id, new_manifest)
```
is more readable and concise. I understand that it makes sense for items to be a list of Manifests though, but that is easily solved (I think) by calling `items.values()` whenever you need the current `items` property

**Comment by martimpassos** [comment]
I did enroll for the hackathon!

**Comment by giacomomarchioro** [comment]
Hi Martim, 
yes  you are right `remove_and_insert_new` was not documented it was only a test, I have improved it now it returns a counter of how many times the ID was found, so you could implement something like this: 

```python
if not remove_and_insert_new(collection, "id_to_check", new_manifest):
    collection.add_manifest_to_items(new_manifest)
```

>  I understand that it makes sense for items to be a list of Manifests though, but that is easily solved (I think) by calling items.values() whenever you need the current items property

Unfortunatly is not the only problem, pyIIIFpres is let's say isomorphic with IIIF presentation standard so you are working to an almost identical structure of the IIIF objects. Two main benefits: 1) theoretically using this library you will also understand the standard itself, no need to learn the standard spec and the package specs 2) easily serializable if the structure is exactly the same it is easier to dump a json . Changing items to a dict would break the isomorphism meaning that during the serialization of the objects you would have to convert that dict in a list again, and this ecxpection I think would required more code than you expect and lower the performance. If you want to give it a try let me know the results.
