### ISSUE TITLE
Load manifest built using pyIIIFpres under Mirador

### ISSUE THREAD

**Issue by faouinti** [giacomomarchioro/pyIIIFpres#17]
Hello,

I tried using the pyIIIFpres module to create my own JSON manifests. I could not load the built manifest under Mirador. Could you please tell me where this problem comes from?

Thank you in advance.

**Comment by giacomomarchioro** [comment]
Hi Faouinti, 
it is hard to tell without knowing what is the problem you get from mirador, and the exact procedure you have performed and the manifest that you created. Can you post the code that you are using for producing the manifest?

**Comment by faouinti** [comment]
Thank you for your quick reply.
Here is the Python code for a Django view that returns the manifest:

```
def manifest_manuscript(request, id):
    from django.http import JsonResponse
    from IIIFpres import iiifpapi3
    from PIL import Image
    
    scheme = request.scheme  # http or https
    hostname = request.META['HTTP_HOST'] 
    iiifpapi3.BASE_URL = scheme+"://"+hostname+"/manuscript/iiif/"+id+"/"
    manifest = iiifpapi3.Manifest()
    manifest.set_id(extendbase_url="manifest.json")
    manifest.add_label("en", Manuscript.objects.get(pk=id).work)
    manifest.add_behavior("paged")

    data = ()
    images = Manuscript.objects.get(pk=id).imagemanuscript_set.all()
    for i, img in enumerate(images):
        i += 1
        image = Image.open(img.image)
        another_data = ("Page "+str(i), image.width, image.height, scheme+"://"+hostname+"/iiif/3/"+img.image.url.split('/')[-1],
                        "/full/max/0/default.jpg")
        data = data + (another_data,)

    for idx, d in enumerate(data):
        idx += 1
        canvas = manifest.add_canvas_to_items()
        canvas.set_id(extendbase_url="canvas/p%s" % idx)  # in this case we use the base url
        canvas.set_height(d[2])
        canvas.set_width(d[1])
        canvas.add_label("en", d[0])
        annopage = canvas.add_annotationpage_to_items()
        annopage.set_id(extendbase_url="page/p%s/1" % idx)
        annotation = annopage.add_annotation_to_items(target=canvas.id)
        annotation.set_id(extendbase_url="annotation/p%s-image" % str(idx).zfill(4))
        annotation.set_motivation("painting")
        annotation.body.set_id("".join(d[3:]))
        annotation.body.set_type("Image")
        annotation.body.set_format("image/jpeg")
        annotation.body.set_width(d[1])
        annotation.body.set_height(d[2])
        s = annotation.body.add_service()
        s.set_id(d[3])
        s.set_type("ImageService3")
        s.set_profile("level1")

    manifest.json_save("mediafiles/manuscripts/manifest/"+id+".json")

    with open("mediafiles/manuscripts/manifest/"+id+".json") as json_file:
        data = json.load(json_file)

    return JsonResponse(data)
```

**Comment by giacomomarchioro** [comment]
Mmm I don't see any error...
Can you make a request and copy and past the JSON file in one bucket like this one https://www.npoint.io/
, and share it with me?

**Comment by faouinti** [comment]
Here is an example of a manifest: [https://iscd.huma-num.fr/manuscript/iiif/1/manifest.json](https://iscd.huma-num.fr/manuscript/iiif/1/manifest.json)

I could not upload it to: [https://mirador-dev.netlify.app/__tests__/integration/mirador/](https://mirador-dev.netlify.app/__tests__/integration/mirador/)

**Comment by giacomomarchioro** [comment]
You have to allow CORS  in your server if you want to display it.  Maybe this can help: [allow cors in django](https://www.geeksforgeeks.org/how-to-enable-cors-headers-in-your-django-project/ ).This is the main issue.

Then: 
```
Manuscript.objects.get(pk=id).work
```

Is not a string is a dictionary  should be possibly like this: 

```
Manuscript.objects.get(pk=id).work['title']
```
Remember to change the language accordingly.

**Comment by faouinti** [comment]
Thank you for your help.

Following your remark, I managed to load this manifest ([https://iscd.huma-num.fr/manuscript/iiif/1/manifest.json](https://iscd.huma-num.fr/manuscript/iiif/1/manifest.json)) in Mirador ([https://mirador-dev.netlify.app/__tests__/integration/mirador/](https://mirador-dev.netlify.app/__tests__/integration/mirador/)). But except the first image, the rest are displayed in pairs. Is it possible to view them image by image? The same result is obtained with the main example ([https://github.com/giacomomarchioro/pyIIIFpres](https://github.com/giacomomarchioro/pyIIIFpres)). Besides, I can't load the same manifest with Mirador v2 (https://vois.huma-num.fr/miradorViewer). Is this normal?

On the other hand, can we add, in addition to the label..., other metadata to our built manifest?

Thanks again.

**Comment by giacomomarchioro** [comment]
> Thank you for your help.
> 
> Following your remark, I managed to load this manifest (https://iscd.huma-num.fr/manuscript/iiif/1/manifest.json) in Mirador ([https://mirador-dev.netlify.app/**tests**/integration/mirador/](https://mirador-dev.netlify.app/__tests__/integration/mirador/)). But except the first image, the rest are displayed in pairs. Is it possible to view them image by image?

This depends on the behaviour property https://iiif.io/api/presentation/3.0/#behavior it should be non-paged

> The same result is obtained with the main example (https://github.com/giacomomarchioro/pyIIIFpres). Besides, I can't load the same manifest with Mirador v2 (https://vois.huma-num.fr/miradorViewer). Is this normal?
> 
I think that Mirador v2 supports only presentation API v2 

> On the other hand, can we add, in addition to the label..., other metadata to our built manifest?
> 
Have a look to this example for adding metadata:
https://github.com/giacomomarchioro/pyIIIFpres/blob/main/examples/0029-metadata-anywhere.py
In the wiki there are more things to know for using the library https://github.com/giacomomarchioro/pyIIIFpres/wiki there is also IIIF slack community for general questions regarding the standards.

**Comment by faouinti** [comment]
It works very well and thank you very much for this valuable information.

**Comment by faouinti** [comment]
Hello,

I really appreciated the use of the pyIIIFpres module for the construction of JSON manifests compliant with IIIF API 3.0.

I use SAS (https://github.com/glenrobson/SimpleAnnotationServer) to save persisting annotations (not local storage). This server is based on Mirador 2, I tested it to annotate built manifests, but it doesn't support Presentation API v3. Is there an older version of pyIIIFpres that supports Presentation API v2 or another solution?

I thought of iiif-prezi, but the library is designed to work with Python 2.7, 3.5, 3.6 and 3.7.

Thank you.

**Comment by giacomomarchioro** [comment]
Hi faounti, unfortunatly pyIIIFpres is dedicated to presentation API 3.0 I haven't developed a version for the previous versions of the standards. :-( I am aware only of iiif-prezi  as an alternative
