### ISSUE TITLE
`set_hightwidth()` adds incorrect keys

### ISSUE THREAD

**Issue by martimpassos** [giacomomarchioro/pyIIIFpres#18]
Hi Giacomo, I just noticed that whenever I use the [`set_hightwidth`](https://github.com/giacomomarchioro/pyIIIFpres/blob/2f059966d1f12233778cd17f0a187c6a6c520f48/IIIFpres/iiifpapi3.py#L620) method, the JSON ends up with keys named "set_width" and "set_height", instead of the expected values of "width" and "height". 

I took a look at the source code but didn't really understand where's the problem. It looks like it correctly calls the separate `set_width` and `set_height` methods...

Here's an example of a `thumbnail` created with `set_hightwidth`:
```
"thumbnail": [
    {
        "id": "https://imaginerio-images.s3.us-east-1.amazonaws.com/iiif/001AAN005121/full/1154,758/0/default.jpg",
        "type": "thumbnail",
        "set_width": 1154,
        "set_height": 758
    }
],
```

**Comment by martimpassos** [comment]
also, `type` should be "Image" and not "thumbnail"

**Comment by giacomomarchioro** [comment]
Hi Martim! Thanks for the comments. That's strange  I out of office now but tomorrow I'll defenly have a look. What version of pyiiifpres at you using?

**Comment by martimpassos** [comment]
I too think it is strange, and that I would have spotted this earlier if it was a problem with pyIIIFpres. Let me investigate further before you spend time on this. 

What's even weirder is that the presentation validator does not complain about these values and Mirador is able to display the thumbs. I only noticed it because bloom-iiif is complaining about my thumbnails.

My lock file seems to point to the latest commit: 

```
"pyiiifpres": {
            "git": "https://github.com/giacomomarchioro/pyIIIFpres",
            "ref": "2f059966d1f12233778cd17f0a187c6a6c520f48"
        },
```

**Comment by giacomomarchioro** [comment]
Hi Martim,
In the meantime, I have corrected the thumbnail problem. In fact, the thumbnail does not have a fixed type it could be "Image", "Video" etc. etc. so now the module will throw an error if you don't set it explicitly. Thanks a lot for spotting that bug!!

I tried to replicate the `set_highwitdh` problem but I couldn't.  Can you share the original code?

I also spot a typo so I think I will deprecate `set_highwitdh` in favour of `set_heigthWidth` in the next version that should be ready in a couple of hours.

**Comment by giacomomarchioro** [comment]
Hi @martimpassos any update regarding this issue?
