### ISSUE TITLE
Rights Statements URI is outdated

### ISSUE THREAD

**Issue by martimpassos** [giacomomarchioro/pyIIIFpres#5]
Ciao Giacomo, thank you so much for this library! It's well structured and probably the first of its kind to support v3.

I'll be adding a few minor issues I encountered while working with your code, but I'm happy to make a PR to address those (they are mainly typos and outdated stuff like this one).

/vocab/ is now /page/ (https://rightsstatements.org/page/CNE/1.0/). Although going to /vocab/CNE/1.0 redirects the user, people will probably be pasting what's in their browser. Also, the `set_rights` method does not accept https

**Comment by giacomomarchioro** [comment]
Hi Martim,
thanks a lot for your feedback!

Unfortunately, currently, the standard does not allow https in the right
statement... :-( see the green box here
https://iiif.io/api/presentation/3.0/#rights, this is something that I
tried to address with the consortium but I can't recall why they choose to
allow only HTTP.

Best regards,
Giacomo


Il giorno ven 3 set 2021 alle ore 17:22 Martim Passos <
***@***.***> ha scritto:
