### ISSUE TITLE
Add support for Brazilian Portuguese

### ISSUE THREAD

**Issue by martimpassos** [giacomomarchioro/pyIIIFpres#6]
[pt-BR should be accepted](https://www.techonthenet.com/js/language_tags.php)

**Comment by giacomomarchioro** [comment]
Hi Martim, 
thanks again for the feedback. You can decide which language tag to allow, see the [project wiki here](https://github.com/giacomomarchioro/pyIIIFpres/wiki/Get-the-language-right) in the section how to add a variant or a script.
 
In your case:

```
from IIIFpres import iiifpapi3,BCP47lang 
iiifpapi3.LANGUAGES = ["pt-BR"] 
# all the rest of your script
```

I decided to encourage the usage of only the subtag to encourage following the [W3C GOLDEN RULE](https://www.w3.org/International/questions/qa-choosing-language-tags#langsubtag):

> Always bear in mind that the golden rule is to keep your language tag as short as possible. Only add further subtags to your language tag if they are needed to distinguish the language from something else in the context where your content is used.

Furthermore is not easy to check the validity of complex subtags and variants, requiring specialized packages. I prefer the user to choose and trust the package that prefers for checking complex user-defined language tags and variants.
