### ISSUE TITLE
Let user know which required attribute is missing on save

### ISSUE THREAD

**Issue by martimpassos** [giacomomarchioro/pyIIIFpres#8]
Seems as easy as printing `attr` [here](https://github.com/giacomomarchioro/pyIIIFpres/blob/33269eb08f90fb43c71617cbc2d5c8ba93783324/IIIFpres/iiifpapi3.py#L82)

**Comment by giacomomarchioro** [comment]
That's a good idea! It was also one of the purposes of defining Required class! I updated the code now in the new version. 
Thanks for your feedback!

P.S. Remember that you can also use `manifest.show_errors_in_browser()` for understanding where is the Required attribute!

**Comment by martimpassos** [comment]
Yes I'm aware of that, `inspect()` also does the trick. Just an idea to make troubleshooting more straightforward

**Comment by giacomomarchioro** [comment]
Suggestion integrated with the latest version.
