### ISSUE TITLE
objid.startswith() assertion bug

### ISSUE THREAD

**Issue by martimpassos** [giacomomarchioro/pyIIIFpres#9]
I have a special character (#) in the URL I'd like to set as ID for a `homepage` object. The library asks for it to be encoded, which I do with `someurl.encode("utf-8")`. 

However, I keep getting `TypeError: startswith first arg must be bytes or a tuple of bytes, not str` [here](https://github.com/giacomomarchioro/pyIIIFpres/blob/33269eb08f90fb43c71617cbc2d5c8ba93783324/IIIFpres/iiifpapi3.py#L218). 

I'm guessing this has to do with `startswith` being both a `str` and `bytes` method. Nonetheless, I tried modifying the basecode with 
```
else:
            if type(objid) == str:
                assert objid.startswith("http"), "ID must start with http or https"
            elif type(objid) == bytes:
                assert objid.startswith(b"http"), "ID must start with http or https"
```
without success. Here's an image for reference:
<img width="758" alt="Screen Shot 2021-09-08 at 12 36 57" src="https://user-images.githubusercontent.com/49573683/132540330-74247278-bcb6-4e3f-9c98-b3adefa1e7f5.png">

**Comment by giacomomarchioro** [comment]
Hi Martim, thanks for reporting it, can you post a minimum working example? I can't reproduce the error at the moment.

**Comment by martimpassos** [comment]
Sure, here you go:
```
#Homepage
some_homepage = iiifpapi3.homepage()
homepage_id = "http://acervos.ims.com.br/portals/#/detailpage/66439"
encoded_homepage_id = homepage_id.encode("utf-8")
print("objid: ",encoded_homepage_id, type(encoded_homepage_id))
some_homepage.set_id(objid=encoded_homepage_id)
```
![image](https://user-images.githubusercontent.com/49573683/132542321-832a8607-a4af-4776-8820-322a2933cbf5.png)

**Comment by giacomomarchioro** [comment]
Thanks a lot Marim, so the root is the specification that says that [special character must be encoded](https://iiif.io/api/presentation/3.0/#6-http-requests-and-responses)  but I am not sure that # should be forbidden. So I have removed from the list. Updateting the module now it will allow to set your current homepage:

#Homepage
from IIIFpres import iiifpapi3
some_homepage = iiifpapi3.homepage()
homepage_id = "http://acervos.ims.com.br/portals/#/detailpage/66439"
some_homepage.set_id(objid=homepage_id)

**Comment by giacomomarchioro** [comment]
Bytheway, following IIIF spec "The URI should not include query parameters or fragments." so I guess the number sign should be avoided? maybe we could use a warning?

**Comment by martimpassos** [comment]
Thanks a lot for the quick action! 

This number sign is coming from my institution's website, which is a bit of a mess and there's not much I can do about it... But a warning sounds good for those who can.

However, shouldn't `.encode("utf-8")` do the trick? For me the problem was the "http" argument on `objid.startswith()`, since I'm passing a bytes object as objid and therefore calling `bytes.startswith()` instead of `str.startswith()`. See [this thread](https://stackoverflow.com/questions/19827615/startswith-typeerror-in-function/19827633).

**Comment by martimpassos** [comment]
I realized that omitting the "#" will still redirect to the correct page, if you want to roll back to prohibiting that character. However the issue is still valid as `set_id` can't handle encoded strings, no matter the special character I use. See [this thread](https://stackoverflow.com/questions/19827615/startswith-typeerror-in-function/19827633), seems to be the same issue with the "http" argument:
<img width="797" alt="Screen Shot 2021-09-08 at 13 37 50" src="https://user-images.githubusercontent.com/49573683/132549627-ec4adedb-1b35-4252-a5d0-9aea7e81190a.png">

**Comment by giacomomarchioro** [comment]
Yes I understand, it seems legitimate. 

> However, shouldn't .encode("utf-8") do the trick?

No, .encode("utf-8") is just encoding it to the utf-8 and returning a byte object, but # is a "normal" utf-8 character. I guess that something like:

`assert str(objid).startswith("http"), "ID must start with http or https" `

could make the error you encounter disappear but you will end dealing with the URI checker you encounter before. The point is just the controversial definition of what is an acceptable URI.

**Comment by martimpassos** [comment]
I see, thanks for the clarification

**Comment by giacomomarchioro** [comment]
> I realized that omitting the "#" will still redirect to the correct page, if you want to roll back to prohibiting that character. However the issue is still valid as `set_id` can't handle encoded strings, no matter the special character I use. See [this thread](https://stackoverflow.com/questions/19827615/startswith-typeerror-in-function/19827633), seems to be the same issue with the "http" argument:
> <img alt="Screen Shot 2021-09-08 at 13 37 50" width="797" src="https://user-images.githubusercontent.com/49573683/132549627-ec4adedb-1b35-4252-a5d0-9aea7e81190a.png">

I understand what you mean. It seems reasonable to allow to pass byte strings. I have to investigate if the results can be consistent, so far I did not find any reason to encode text in utf-8. I will have a look.

**Comment by martimpassos** [comment]
That was just based on my assumption that encoding would resolve the issue. With your input I realize this won't 'fix' anything...
